### ISSUE TITLE
CloudBase CLI用npm安装出现错误，用yarn安装成功,但却查询不到版本

### ISSUE THREAD

**Issue by Mazhangchi** [TencentCloudBase/cloudbase-cli#12]
Microsoft Windous[版本6.1.7601]
版权所有（c）2009 Microsoft Corporation。保留所有权利。
npm安装提示：
C:\ Users\ tmp249>npm i-g acloudbase/cli 
npm WARN deprecated requeste2.88.2: request has been deprecated, see https://git hub. com/request/request/issues/3142
D:\ Program Files\ node js\ node_global\ tcb ->D:\ Program Files\ node js\ node_global\n ode_modules\@ cloudbase\ cli\ bin\ tcb. js 
D:\ Program Files\ node js\ node_global\ cloudbase->D:\ Program Files\ node js\ node_9l obal\ node_modules\ Qcloudbase\ cli\ bin\ cloudbase. js 
npm WARN ws07.3.0 requires a peer of bufferutila4.0.1 but none is installed. Yo u must install peer dependencies yourself.
npm WARN ws07.3.0 requires a peer of utf-8-validatee"5.0.2 but none is installed You must install peer dependencies yourself.
+acloudbase/cli0.7.4
added 392 packages in 300.742s

yarn安装提示：
C:\Users\tmp249>yarn global add acloudbase/cli yarn 9lobal u1.22.4
[1/4]Resoluing packages..
[2/4]Fetching packages...
[3/4]Linking dependencies...
[4/4]Building fresh packages...
success Installed"dcloudbase/cli80.7.4"with binaries：
-tcb
-cloudbase 
Done in 3.77s.

 查询版本提示：
C:\Users\tmp249>cloudbase-u cloudbase不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by chhpt** [comment]
请问你的 Node  版本是多少呢
