### ISSUE TITLE
部署的时候报 MaxListenersExceededWarning: Possible EventEmitter memory leak detected.  这个错误

### ISSUE THREAD

**Issue by chao** [TencentCloudBase/cloudbase-cli#17]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/55872/98636739-67318d80-2362-11eb-86a8-02b544bf1496.png">

(node:1723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 tcbExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit

不确定是我的云函数问题还是cloudbase-cli的问题，麻烦帮忙看看。

**Comment by chao** [comment]
用命令`tcp fn deploy --all`部署的时候如果云函数比较多就会出错。

错误信息：
```
✖ [CreateFunction] Your current request times equals to `11` in a second, which exceeds the frequency limit `10` for a second. Please reduce the frequency of calls.
18
ac0d4585-90f9-4d0b-a5e4-7520cba95cc8
19
script returned exit code 1
```
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/55872/99218423-6b075900-2815-11eb-8a3f-f16069f7edae.png">

**Comment by chao** [comment]
如果腾讯云有只能并发10个的限制的话cli工具是不是应该分批部署呢？

**Comment by chhpt** [comment]
目前同时部署多个云函数尚有一些问题，建议不要同时部署过多的云函数
