### ISSUE TITLE
npm安装@cloudbase/cli后运行命令提示“未对文件tcb.ps1 进行数字签名。无法在当前系统上 运行该脚本”

### ISSUE THREAD

**Issue by wopelo** [TencentCloudBase/cloudbase-cli#18]
操作系统windows10
node版本v12.14.1
执行 npm i -g @cloudbase/cli 并为抛出任何错误
执行  cloudbase -v 报错如下
`tcb : 无法加载文件 D:\nodejs\node_global\tcb.ps1。未对文件 D:\nodejs\node_global\tcb.ps1 进行数字签名。无法在当前系统上
运行该脚本。有关运行脚本和设置执行策略的详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execu
tion_Policies。
所在位置 行:1 字符: 1
 tcb login --key
     CategoryInfo          : SecurityError: (:) []，PSSecurityException
     FullyQualifiedErrorId : UnauthorizedAccess`

**Comment by chhpt** [comment]
此为 Windows 系统对脚本执行权限的限制报错，请修改系统设置，允许脚本执行
