### ISSUE TITLE
层函数的相关命令希望能增加以下功能

### ISSUE THREAD

**Issue by chao** [TencentCloudBase/cloudbase-cli#19]
1、希望能够在创建层的时候允许指定运行环境，而不是一次性把PHP、Nodejs都加上。
2、在进行函数绑定的时候希望能够通过参数指定所选的层和版本，例如--layer xxx@latest。这样就对应xx层的最新版。
3、希望能够一次绑定多个函数。

**Comment by chhpt** [comment]
函数层已暂时停止支持
