### ISSUE TITLE
默认执行tcb functions:deploy报错，需要单独部署云函数

### ISSUE THREAD

**Issue by liminjun** [TencentCloudBase/cloudbase-cli#5]
默认执行tcb functions:deploy报错：
![image](https://user-images.githubusercontent.com/966009/77071032-4d83b480-6a26-11ea-9500-a811eeaf8c0f.png)

单个部署可以成功：
![image](https://user-images.githubusercontent.com/966009/77071057-570d1c80-6a26-11ea-862f-c7cdf0cd3ace.png)

**Comment by chhpt** [comment]
@liminjun 已收到问题，会在近期 fix

**Comment by chhpt** [comment]
@liminjun 此问题已修复，请更新 CLI 到最新版本
