### ISSUE TITLE
functions.code.update 不会安装node dependencies

### ISSUE THREAD

**Issue by CharlesHGong** [TencentCloudBase/cloudbase-cli#8]
想在ci 里automate 云函数同步上传。
但是functions.code.update 不会安装node dependencies 反而替换掉了原有的node_modules。
functions.deploy 也不能用 会报错部署失败函数已存在

希望这个method 或者有个method 可以和小程序里的 “上传并部署：云端安装依赖”一样 上传所有code 并云端安装依赖

**Comment by chhpt** [comment]
@CharlesGong-BOT 
建议阅读官方文档：https://docs.cloudbase.net/cli/intro.html，CLI 提供了上传并部署的能力。

code:update 只会更新代码，如果 node_modules 是你手动上传的，自然会覆盖。
